name: Pipeline Atividade Final DevSecOps

on:
  push: # Escolhido esse modo pois estava usando GitHub Desktop, dessa forma, a cada push de modificação do código, efetuaria a analise do Pipeline
    branches:
      - main

permissions:
  contents: write

jobs:

  # Atenção Fabiano! 
  # Job referente a analise do código de acordo com a própria analise via NPM do Node 
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes unitários
        run: npm test -- --watchAll=false

      - name: Analise por Extencao de Arquivo
        run: npx eslint . --ext .js,.jsx || true

  # Atenção Fabiano!
  # Unificado em um apenas para facilitar a verificação e Deploy da Aplicação, estava enfrentando erros na execução
  build-and-deploy:
    runs-on: ubuntu-latest 
    needs: code-analysis #Fabiano, aprendi essa questão para exigir que o passo anterior seja 100% concluido para sim seguir para esse!

    steps:
      - name: Verificação do código
        uses: actions/checkout@v3

      - name: Configurar Node 
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências do Node
        run: npm install

      - name: Build da aplicação
        run: npm run build

      - name: Deploy para poder acessar pelo GihHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build